export {
    GET_ALL_CUSTOMER_INFO,
    GET_CUSTOMER_BASIC_INFO,
    PUT_CUSTOMER_INFO,
    PUT_CUSTOMER_INFO_FAILED,
    PUT_CUSTOMER_INFO_SUCCESS,
    REGISTER_ACCOUNT_CUSTOMER,
    REGISTER_ACCOUNT_FAILED,
    REGISTER_ACCOUNT_SUCCESS,
    SET_ALL_CUSTOMER_INFO_FAILED,
    SET_ALL_CUSTOMER_INFO_SUCCESS,
    SET_CUSTOMER_ACCUMULATED_FAILED,
    SET_CUSTOMER_ACCUMULATED_SUCCESS,
    SET_CUSTOMER_BASIC_INFO_FAILED,
    SET_CUSTOMER_BASIC_INFO_SUCCESS,
} from './account/accountSlice';
export { RESET_LOCATION_VALUE, SET_LOCATION_VALUE } from './address/addressSlice';
export {
    RESET_VIDEO_OPTION,
    SET_APP_START,
    SET_CHAT_STATE,
    SET_CONNECTED_INTERNET,
    SET_GIFTS_ORDER,
    SET_INDEX_ORDER_TAB,
    SET_NUM_SHOW_PHONE_CONFIRM,
    SET_NUM_SPIN_ATTENDANCE_MODAL,
    SET_ORDER_RETURNS_OPTIONS,
    SET_STATUS_CART_SWR,
    SET_STATUS_MESSAGE,
    SET_VIDEO_OPTION,
} from './apps/appsSlice';
export {
    AUTH_FAILED,
    AUTH_SUCCESS,
    LOGOUT_CURRENT_USER,
    SIGNIN_WITH_ACCOUNT,
    SIGNIN_WITH_APPLE,
    SIGNIN_WITH_FACEBOOK,
    SIGNIN_WITH_GOOGLE,
} from './auth/authSlice';
//action not handle, just call
export const SET_USER_LOGIN = 'SET_USER_LOGIN';
export const LOGOUT_CURRENT_USER_SUCCESS = 'LOGOUT_CURRENT_USER_SUCCESS';
