import { useTheme } from 'hooks';
import { Platform, StyleSheet } from 'react-native';

const useStyles = () => {
    const { theme } = useTheme();
    return StyleSheet.create({
        safe_view: {
            flex: 1,
            backgroundColor: theme.colors.white_[10],
        },
        view_container: {
            flex: 1,
            position: 'relative',
        },
        //header
        header_view_container: {
            shadowColor: '#000',
            shadowOffset: {
                width: 0,
                height: 3,
            },
            shadowOpacity: 0.29,
            shadowRadius: 4.65,
            elevation: 7,
            zIndex: 9999,
            backgroundColor: theme.colors.white_[10],
        },
        header_center_style: {
            color: theme.colors.slate[900],
            fontSize: theme.typography.title1,
            fontWeight: 'bold',
        },
        touch_img_user_header: {
            borderRadius: 100,
            width: theme.dimens.scale(40),
            aspectRatio: 1,
            backgroundColor: theme.colors.white_[10],
            ...theme.styles.shadow1,
        },
        // content chat
        view_list: {
            flex: 1,
            backgroundColor: theme.colors.grey_[100],
        },
        view_wrap_send: {
            alignItems: 'flex-end',
            marginVertical: theme.spacings.small,
        },
        view_message_item: {
            maxWidth: '80%',
        },
        view_send: {
            paddingHorizontal: theme.spacings.medium,
            paddingVertical: theme.spacings.small,
            backgroundColor: theme.colors.cyan[100],
            // backgroundColor: theme.colors.white_[10],
            borderRadius: 5,
            ...theme.styles.shadow2,
        },
        view_reply_send: {
            flexDirection: 'row',
            backgroundColor: theme.colors.cyan['50'],
            minWidth: '100%',
            padding: theme.spacings.small,
            // borderRadius: 10,
            marginBottom: theme.spacings.small,
            borderLeftWidth: 3,
            borderColor: theme.colors.cyan['200'],
            borderRadius: 5,
        },
        txt_send: {
            color: theme.colors.black_[10],
            fontSize: theme.typography.body2,
        },

        view_wrap_receive: {
            marginVertical: theme.spacings.small,
            alignItems: 'flex-start',
        },
        view_receive: {
            paddingHorizontal: theme.spacings.medium,
            paddingVertical: theme.spacings.small,
            backgroundColor: theme.colors.white_[10],
            ...theme.styles.shadow2,
            // borderTopLeftRadius: 20,
            // borderTopRightRadius: 20,
            // borderBottomRightRadius: 20,
            borderRadius: 5,
        },
        view_reply_receive: {
            flexDirection: 'row',
            backgroundColor: theme.colors.grey_[300],
            width: '100%',
            padding: theme.spacings.small,
            marginBottom: theme.spacings.small,

            borderLeftWidth: 3,
            borderColor: theme.colors.grey_[400],
            borderRadius: 5,
        },
        txt_receive: {
            fontSize: theme.typography.body2,
        },
        view_image: {
            borderWidth: 1,
            borderColor: theme.colors.grey_[200],
            borderRadius: 5,
            overflow: 'hidden',
            padding: 0,
        },
        view_video: {
            width: theme.dimens.width * 0.6,
            aspectRatio: 1,
            borderRadius: 5,
            overflow: 'hidden',
        },
        view_scroll_end: {
            position: 'absolute',
            bottom: 5,
            alignSelf: 'center',
        },
        view_wrap_input: {
            // paddingHorizontal: theme.spacings.small,
            padding: theme.spacings.medium,
            backgroundColor: theme.colors.white_[10],

            borderTopWidth: 1,
            borderTopColor: theme.colors.grey_[100],
        },
        view_relay_info: {
            flex: 1,
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            backgroundColor: theme.colors.main['50'],
            padding: theme.spacings.small,
            marginBottom: theme.spacings.small,
            borderLeftWidth: 4,
            borderLeftColor: theme.colors.main['600'],
        },
        view_input_chat: {
            backgroundColor: theme.colors.grey_[100],
            borderRadius: 20,
            flexDirection: 'row',
            paddingVertical: Platform.OS === 'ios' ? theme.dimens.sizeElement('md') : undefined,
            paddingHorizontal: theme.spacings.tiny,
            alignItems: 'center',
        },
        input_style: {
            flex: 1,
            marginLeft: theme.spacings.small,
            fontSize: theme.typography.body2,
            color: theme.colors.grey_[600],
        },
        touch_image_select: {
            width: theme.dimens.scale(50),
            aspectRatio: 1,
            borderWidth: 1,
            borderColor: theme.colors.grey_[200],
            marginRight: theme.spacings.tiny,
            position: 'relative',
            borderRadius: 5,
            overflow: 'hidden',
        },
        view_icon_delete_img: {
            position: 'absolute',
            top: 0,
            right: 0,
            zIndex: 9999,
        },
        view_icon_video: {
            position: 'absolute',
            justifyContent: 'center',
            alignItems: 'center',
            top: 0,
            bottom: 0,
            left: 0,
            right: 0,
            zIndex: 9999,
        },
        //reply
        view_wrap_options: {
            backgroundColor: theme.colors.white_[10],
            borderRadius: 5,
            paddingHorizontal: theme.spacings.small,
        },
        touch_option: {
            borderBottomWidth: 1,
            borderTopWidth: 1,
            borderColor: theme.colors.grey_[200],
            padding: theme.spacings.medium,
        },
        view_img_reply: {
            flex: 0.17,
            aspectRatio: 1,
            backgroundColor: theme.colors.black_[10],
            borderRadius: 3,
            overflow: 'hidden',
        },
        txt_more_reply: {
            position: 'absolute',
            bottom: 0,
            left: 0,
            right: 0,
            backgroundColor: theme.colors.black_[10],
            textAlign: 'center',
            color: theme.colors.white_[10],
        },
        view_icon_video_reply: {
            position: 'absolute',
            top: 0,
            bottom: 0,
            left: 0,
            right: 0,
            justifyContent: 'center',
            alignItems: 'center',
        },
        //sheet seller
        touch_option_seller: {
            padding: theme.spacings.medium,
            borderTopWidth: 1,
            borderColor: theme.colors.grey_[200],
            alignItems: 'center',
        },
        // bargain
        view_bargain: {
            width: theme.dimens.width * 0.8,
            backgroundColor: theme.colors.white_[10],
            // padding: theme.spacings.small,
            borderRadius: 10,
            // borderWidth: 1,
            // borderColor: theme.colors.main["50"],

            ...theme.styles.shadow3,
        },
        view_bargain_title: {
            padding: theme.spacings.tiny,
            borderTopLeftRadius: 10,
            borderTopRightRadius: 10,
        },
        view_bargain_info: {
            flexDirection: 'row',
            padding: theme.spacings.medium,
            // marginBottom: theme.spacings.small,
            // backgroundColor: theme.colors.grey_[100],
            borderRadius: 5,
        },
        view_sheet_input: {
            padding: theme.spacings.small,
            backgroundColor: theme.colors.white_[10],
            borderTopLeftRadius: 5,
            borderTopRightRadius: 5,
        },
        view_wrap_bargain_input: {
            flexDirection: 'row',
            alignItems: 'center',
            height: theme.dimens.verticalScale(35),
        },
        view_bargain_input_left: {
            flex: 0.3,
            backgroundColor: theme.colors.grey_[300],
            height: '100%',
            justifyContent: 'center',
            alignItems: 'center',
            paddingVertical: theme.spacings.small,
            borderTopLeftRadius: 5,
            borderBottomLeftRadius: 5,
        },
        input_bargain_: {
            flex: 0.4,
            padding: 0,
            height: '100%',
            textAlign: 'center',
            borderWidth: 1,
            borderColor: theme.colors.grey_[300],
            fontSize: theme.typography.body1,
            color: theme.colors.grey_[500],
        },
        view_bargain_input_right_qty: {
            flex: 0.3,
            flexDirection: 'row',
            backgroundColor: theme.colors.grey_[300],
            height: '100%',
            borderTopRightRadius: 5,
            borderBottomRightRadius: 5,
        },
        touch_plush_minus: {
            flex: 0.5,
            height: '100%',
            justifyContent: 'center',
            alignItems: 'center',
        },
        view_bargain_input_right_price: {
            flex: 0.3,
            flexDirection: 'row',
            backgroundColor: theme.colors.grey_[300],
            height: '100%',
            justifyContent: 'center',
            alignItems: 'center',
            borderTopRightRadius: 5,
            borderBottomRightRadius: 5,
        },
        txt_bargain_accept: {
            padding: theme.dimens.verticalScale(2),
            paddingHorizontal: theme.spacings.small,
            backgroundColor: theme.colors.green['50'],
            borderRadius: 3,
            color: theme.colors.green['500'],
            fontSize: theme.typography.sub2,
        },
        txt_bargain_reject: {
            padding: theme.dimens.verticalScale(2),
            paddingHorizontal: theme.spacings.small,
            backgroundColor: theme.colors.red['50'],
            borderRadius: 3,
            color: theme.colors.red['500'],
            fontSize: theme.typography.sub2,
        },
        txt_bargain_cancel: {
            padding: theme.dimens.verticalScale(2),
            paddingHorizontal: theme.spacings.small,
            backgroundColor: theme.colors.grey_[200],
            borderRadius: 3,
            color: theme.colors.grey_[400],
            fontSize: theme.typography.sub2,
        },
    });
};

export default useStyles;
